title: Nicholas Magal # your name (or website title) here
logo: "/IMG_2141.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Greetings! I am a data science professional with a passion for applying machine learning to high impact problems. I am upcoming Associate Data Scientist in the IDAP program at NextEra, and have previous professional expierence at Alstom and Nielsen.
  <br><br>
  I received my Master's in Music and Technology from Carnegie Mellon University, where I studied machine learning applications to music.  
  <br><br>
  <a href="https://www.linkedin.com/in/nicholas-magal-45214012a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
