title: Nicholas Magal # your name (or website title) here
logo: "/IMG_2141.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Greetings! I am a Data Scientist at NextEra, with a passion for applying machine learning to high impact problems. Some of my primary recent work has been automating processes within NextEra's nuclear fleet, speeding up many things that used to be a manual process. 
  <br><br>
  This website features a subset of some of the most interesting side projects I have completed. If anything is of interest, please feel free to reach out to discuss further. 
  <br><br>

  <a href="https://www.linkedin.com/in/nicholas-magal-45214012a/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
